### ISSUE TITLE
RHEL8 install fails due to missing docker-ce-edge repository

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#123]
### Version Information
Ansible: `2.9.9`

Role: `2.7.0`

### Steps to Reproduce
Fresh install of RHEL8 running a simple play that includes this role with default vars.

### Expected Behavior
Succesful install

### Actual Behavior
Failed at this task: Disable Docker CE repository channels (Fedor/CentOS/RedHat)

```
{
    "msg": "non-zero return code",
    "cmd": "yum-config-manager --disable docker-ce-edge",
    "stdout": "Updating Subscription Management repositories.",
    "stderr": "Error: No matching repo to modify: docker-ce-edge.",
    "rc": 1,
    "start": "2020-10-05 16:14:27.969840",
    "end": "2020-10-05 16:14:28.790724",
    "delta": "0:00:00.820884",
    "changed": false,
    "invocation": {
        "module_args": {
            "warn": false,
            "_raw_params": "yum-config-manager --disable docker-ce-edge",
            "_uses_shell": true,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "argv": null,
            "chdir": null,
            "executable": null,
            "creates": null,
            "removes": null,
            "stdin": null
        }
    },
    "stdout_lines": [
        "Updating Subscription Management repositories."
    ],
    "stderr_lines": [
        "Error: No matching repo to modify: docker-ce-edge."
    ],
    "_ansible_no_log": false,
    "item": "edge",
    "ansible_loop_var": "item",
    "_ansible_item_label": "edge"
}
```

### References
-

**Comment by janorn** [comment]
Adding a bogus repo called docker-ce-edge makes the install to be successful.

**Comment by janorn** [comment]
```
$ curl -s https://download.docker.com/linux/centos/docker-ce.repo | grep '\['
[docker-ce-stable]
[docker-ce-stable-debuginfo]
[docker-ce-stable-source]
[docker-ce-test]
[docker-ce-test-debuginfo]
[docker-ce-test-source]
[docker-ce-nightly]
[docker-ce-nightly-debuginfo]
[docker-ce-nightly-source]
```

**Comment by haxorof** [comment]
Thanks for reporting this! I will have a look at it.

**Comment by haxorof** [comment]
I managed to reproduce the error you got by running the test suite I got. I will correct this but since it is related to this `edge` channel which they finally removed after so long time then I will do some more cleanups. Will do a new release either today or tomorrow.

Thanks again for reporting this problem! :)

**Comment by haxorof** [comment]
Release 3.0.0 include the fix. See changelog for more info: https://github.com/haxorof/ansible-role-docker-ce/blob/master/CHANGELOG.md

**Comment by janorn** [comment]
Thanks!

Works perfectly. Default settings also picks up containerd from docker repo.
