### ISSUE TITLE
Tasks related to removal uses yum instead of dnf for RHEL 8

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#124]
### Version Information
Ansible: `2.9.9`
Role: `3.0.0`

### Actual Behavior
RHEL7 uses yum

### New/Changed Behavior
RHEL8 uses dnf

### Issues
The removal tasks is checking for RedHat and looks for yum cache dirs which don't exist on RHEL8

**Comment by haxorof** [comment]
Thanks! I think I never checked if removal worked on RHEL 8. Think that would be easy to fix.

**Comment by haxorof** [comment]
Fixes available on master but will do a release later today or tomorrow

**Comment by janorn** [comment]
Where did Fedora go?

https://github.com/haxorof/ansible-role-docker-ce/blob/5a98977d09459c46d80ebb382e205eacb25cc465/tasks/remove-docker.yml#L137

**Comment by haxorof** [comment]
> Where did Fedora go?
> 
> https://github.com/haxorof/ansible-role-docker-ce/blob/5a98977d09459c46d80ebb382e205eacb25cc465/tasks/remove-docker.yml#L137

Good catch! my mistake.. will be fixed in commit I will do before new release.
