### ISSUE TITLE
WSL2: Failing to check docker daemon status

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#127]
### Version Information
Ansible: `2.9.6`
Role: `3.1.0`

### Steps to Reproduce
Using this role in Ubuntu 20.04 in WSL2 (Windows Subsystem for Linux)

### Expected Behavior
Ansible run finish correctly

### Actual Behavior
```
TASK [haxorof.docker_ce : Setup Docker environment file /etc/default/docker] *******************************************
ok: [127.0.0.1]

TASK [haxorof.docker_ce : Ensure /etc/docker directory exists] *********************************************************
ok: [127.0.0.1]

TASK [haxorof.docker_ce : Configure Docker daemon (file)] **************************************************************
skipping: [127.0.0.1]

TASK [haxorof.docker_ce : Fetch Docker daemon status] ******************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "one of the following is required: state, enabled"}

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=34   changed=0    unreachable=0    failed=1    skipped=26   rescued=0    ignored=0
```

**Comment by janorn** [comment]
WSL2 doesnt support systemd.

**Comment by janorn** [comment]
Perhaps use:

```
- name: Check service state
  service_facts:
  register: services_state
```

**Comment by haxorof** [comment]
Thanks for reporting this. Will see if I get some time into looking into it this weekend.

Cheers!

**Comment by haxorof** [comment]
Thanks for the PR but I took most of what you did in the PR and improved the things I mentioned. Will reject the PRs and push my changes.

**Comment by janorn** [comment]
Been busy so I didn't have time to look at it.

**Comment by haxorof** [comment]
> Been busy so I didn't have time to look at it. 

No worries, here too but got a slot yesterday and ran through all regression tests. Please try the new version I just released and hope that will work in WSL2 now. 😊

**Comment by janorn** [comment]
I tried the new code and it works! Thanks.
