### ISSUE TITLE
Python docker Version 5 Drops support for Python 2

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#136]
I assume this could cause issues on centos 7 for instance. 

Change log
5.0.0

Breaking changes
- Remove support for Python 2.7
- Make Python 3.6 the minimum version supported

**Comment by janorn** [comment]
Possible solution in vars:

"docker{​​​​​{​​​​​ '<5.0.0' if ansible_python_version is version('3.0.0', '<') }​​​​​}​​​​​"

**Comment by haxorof** [comment]
Thanks @janorn for letting me know about this. It can indeed cause issues for distributions using Python 2 like CentOS 7.

Also thanks for suggested solution. Will look into it!

**Comment by haxorof** [comment]
Just some additional notes to consider when doing fix.
Since Docker SDK for Python (docker) is dropping Python 2 support then docker-compose which is Python based must also be lower than "1.29.0" since in that version it depends on docker 5.0.0

**Comment by haxorof** [comment]
I will do a new release soon.

Thanks @janorn for the suggested solution which made it a bit quicker to implement the fix. 👍
