### ISSUE TITLE
Docker plugin install seems to be missing "item.args"

### ISSUE THREAD

**Issue by janorn** [haxorof/ansible-role-docker-ce#142]
In this code there is no reference to the args parameter in the dict. End result if you try to use the Opa example is that it will not find the policy file.

https://github.com/haxorof/ansible-role-docker-ce/blob/afe2eb7dd6371e0471f08a66d15d414c731473ea/tasks/configure-docker/configure-docker-plugins.yml#L17-L21

Perhaps this was the intended code?

```
"(docker plugin install --grant-all-permissions --alias {{ item.alias | default(item.name) }} {{ item.name }} {{ item.args }} \ 
     && echo 'installed') || echo 'nop'"
```

**Comment by haxorof** [comment]
Thanks @janorn for reporting this! I actually think I must have missed the args and is an optional thing to have. In the opa case they do not require that args to be set. Will correct this.
