### ISSUE TITLE
Provisioning Host in Preparation for "dm.directlvm_device=/dev/sdb1"

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#15]
It's a shot in the dark that you might know this (it involves Vagrant), but here goes.

I'm trying to see if I can satisfy the "1.1 Ensure a separate partition for containers has been created" check.

The following configurations are stripped down to remove anything that's not directly related to this question.

The `Vagrantfile` happens to use the [`vagrant-persistent-storage` plugin](https://github.com/kusnier/vagrant-persistent-storage) (which I just discovered today when looking for a solution). Even if you don't know the particulars of that plugin, maybe you could tell me what the end state of the disk configuration would need to be for the role's `"dm.directlvm_device=/dev/sdb1"` configuration to use it.

`Vagrantfile`:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :slave do |slave|
        
      if Vagrant.has_plugin?("vagrant-persistent-storage")
        slave.persistent_storage.enabled = true
        slave.persistent_storage.location = "~/development/sourcehdd.vdi"
        slave.persistent_storage.size = 5000
        slave.persistent_storage.filesystem = 'ext4'
        #slave.persistent_storage.partition = false
      end
    
    end
    
    slave.vm.hostname = "centos-jenkins-slave"
    
    # Disable the new default behavior introduced in Vagrant 1.7, to
    # ensure that all Vagrant machines will use the same SSH key pair.
    # See https://github.com/mitchellh/vagrant/issues/5005
    slave.ssh.insert_key = false
    
    slave.vm.box = "geerlingguy/centos7"
    
    slave.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
    end
    
  end

end
```

`playbook.yml`:

```
  roles:
    - role: haxorof.docker-ce
      docker_enable_audit: true
      docker_enable_ce_edge: true
      docker_daemon_config:
        icc: false
        init: true
        userns-remap: default
        disable-legacy-registry: true
        live-restore: true
        userland-proxy: false
        log-driver: journald
        storage-driver: devicemapper
        storage-opts:
          - "dm.directlvm_device=/dev/sdb1"
```

Which yields:

```
$ sudo fdisk -l

Disk /dev/sda: 85.9 GB, 85899345920 bytes, 167772160 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x0009da9f

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     2099199     1048576   83  Linux
/dev/sda2         2099200   167772159    82836480   8e  Linux LVM

Disk /dev/sdb: 5242 MB, 5242880000 bytes, 10240000 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x00000000

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1               1    10233404     5116702   8e  Linux LVM

Disk /dev/mapper/centos-root: 53.7 GB, 53687091200 bytes, 104857600 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/centos-swap: 1073 MB, 1073741824 bytes, 2097152 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/centos-home: 30.1 GB, 30056382464 bytes, 58703872 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/vps-vps: 5234 MB, 5234491392 bytes, 10223616 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

...and:

```
$ sudo df

Filesystem                                                        1K-blocks      Used Available Use% Mounted on
/dev/mapper/centos-root                                            52403200   1198136  51205064   3% /
devtmpfs                                                             239084         0    239084   0% /dev
tmpfs                                                                250008         0    250008   0% /dev/shm
tmpfs                                                                250008      4476    245532   2% /run
tmpfs                                                                250008         0    250008   0% /sys/fs/cgroup
/dev/sda1                                                           1038336    156620    881716  16% /boot
/dev/mapper/centos-home                                            29337604     35892  29301712   1% /home
192.168.56.1:/Users/jjackson/.vagrant.d/cache/geerlingguy/centos7 487260160 280297600 206706560  58% /tmp/vagrant-cache
vagrant                                                           487260160 280553620 206706540  58% /vagrant
tmpfs                                                                 50004         0     50004   0% /run/user/1000
```

Not that I really know what I'm doing with any of the above, but I keep ending up with the following, despite different attempts:

```
TASK [haxorof.docker-ce : Enable and start Docker service] *********************
fatal: [slave]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by jamiejackson** [comment]
Looks like you already [answered my question in your test suite](https://github.com/haxorof/ansible-role-docker-ce/blob/8677e61202bf3b685c2171005c29495c42ea6e91/tests/Vagrantfile#L10-L17)!

**Comment by jamiejackson** [comment]
Hmm, I'd thought that with the role and your Vagrantfile, and the playbook snippet above, that I'd stop getting:

```
[WARN] 1.1  - Ensure a separate partition for containers has been created
```
I that to be expected?

Also, maybe this would be for another GH issue, but I'll bring it up here first:

I do get a couple of other `WARN`s, too:

```
...
[WARN] 2.11 - Ensure that authorization for Docker client commands is enabled
...
[WARN] 4.5  - Ensure Content trust for Docker is Enabled
...
```
I haven't read up on those yet, but are those to be expected, as well?

**Comment by haxorof** [comment]
The `Vagrantfile` I have under tests is something I just did quickly but to do some tests. I will revisit it and see if I can provide with a better example.

Related to the 1.1 section I think that even if you configure Docker to use `devicemapper` and `direct-lvm` it will complain about 1.1 because it only looks for `/var/lib/docker` shall exist in file `/etc/fstab`. 

Even if you do not pass this check it is not a big problem when you use `direct-lvm` because the images etc will not be stored under `/var/lib/docker` anyway, only some smaller set of files. But to pass this check it is easy just to create another logical volume and mount if under `/var/lib/docker` and then it will appear in `/etc/fstab`.

**Comment by haxorof** [comment]
Now I have updated the `Vagrantfile` under `tests` directory. After you have executed `vagrant up` you will see one example of to PASS the 1.1. After the box is up and running you will also find Docker Bench for Security under `/home/vagrant/docker-bench-security`.

Please try and have a look. Note! I use one Ansible [playbook](https://github.com/haxorof/ansible-role-docker-ce/blob/master/tests/test_config_storage_prepare.yml) as workaround to prepare the box before setting up Docker.

**Comment by haxorof** [comment]
@jamiejackson Did it work out for you in the end?

Cheers!

**Comment by jamiejackson** [comment]
I'll try to circle back around to this in the next couple days, thanks!

**Comment by jamiejackson** [comment]
Looks like 1.1 passes, thanks!

```
$ sudo sh docker-bench-security.sh | grep "\(WARN\|partition\)"
[PASS] 1.1  - Ensure a separate partition for containers has been created
[WARN] 2.8  - Enable user namespace support
[WARN] 2.11 - Ensure that authorization for Docker client commands is enabled
[WARN] 4.5  - Ensure Content trust for Docker is Enabled
```

**Comment by jamiejackson** [comment]
Now that I'm taking a closer look, I have some questions:

[test_config_storage_prepare.yml](https://github.com/haxorof/ansible-role-docker-ce/blob/b0e86eb9314db3419c3ff30ef230518bad3fbae5/tests/test_config_storage_prepare.yml ) sets up two partitions, `sdb1` (`var/lib/docker`) and `sdb2`.

Then, [test_config_storage.yml](https://github.com/haxorof/ansible-role-docker-ce/blob/b0e86eb9314db3419c3ff30ef230518bad3fbae5/tests/test_config_storage.yml) refers to `sdb2`.

```yml
      storage-opts:
        - "dm.directlvm_device=/dev/sdb2"
```

I don't understand what `sdb2` is for. Could you explain or point to documentation that might help?

**Comment by haxorof** [comment]
Related to the test configuration in `test_config_storage.yml` it is `sdb2` where all the images and containers will be stored when `direct-lvm` is used.

Below are two links I recommend you to read which go into this in more detail:
https://docs.docker.com/engine/userguide/storagedriver/selectadriver/
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

Hope it will be more clear now!

Cheers!
