### ISSUE TITLE
fstype ext4 vs. xfs

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#22]
Hello again, @haxorof,

Is `ext4` the recommended fstype for CentOS for Docker? (I see that you changed over the tests from `xfs` to `ext4` in [a recent commit](https://github.com/haxorof/ansible-role-docker-ce/commit/b0e86eb9314db3419c3ff30ef230518bad3fbae5#diff-0e48f0ebc1d5ce50d1872d84efa5c318).)

**Comment by haxorof** [comment]
Hi @jamiejackson 

I am not sure what Docker recommend for CentOS but I have experienced problems using xfs in the past and also depends on what kind of workload you have on the machine. I you google a bit around this you will finds some different answers but if want it to work more smooth on both CentOS/RHEL 7.x then ext4 is to choose I think. Here is one discussion for example: https://community.centminmod.com/threads/using-docker-on-centos-7-choose-ext4-over-xfs.12492/

**Comment by jamiejackson** [comment]
Got it, thanks again.
