### ISSUE TITLE
Support for Linux Mint (or Hack Suggestion?)

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#24]
There's one machine I'm targeting which is running Linux Mint:

```json
"ansible_distribution": "Linux Mint",
"ansible_distribution_file_parsed": true,
"ansible_distribution_file_path": "/etc/os-release",
"ansible_distribution_file_variety": "NA",
"ansible_distribution_major_version": "18",
"ansible_distribution_release": "serena",
"ansible_distribution_version": "18.1",
```

I hacked up the role locally to get it to work (it's the same as Ubuntu 16.04), but I'm wondering if there's a way to override these facts, for a given host, to fool the role into thinking it's Ubuntu 16.04. Do you happen to know?

Otherwise, the role itself could support Linux Mint, but I'm not sure how much effort this project would want to put into supporting more obscure distros.

**Comment by haxorof** [comment]
So Docker works on Linux Mint even though Docker does not support it according to their matrix? If it is similar to Ubuntu 16.04 I can see what can be done

**Comment by jamiejackson** [comment]
Well, empirically, it seems to work, but since it's not in the [matrix](https://success.docker.com/Policies/Compatibility_Matrix), it might not make sense to give it first-class treatment.

FWIW, here's a Mint/Ubuntu version mapping: https://en.wikipedia.org/wiki/Linux_Mint_version_history

**Comment by haxorof** [comment]
@jamiejackson : I have done a commit to support Linux Mint 18. Can you verify that it works for you?

**Comment by jamiejackson** [comment]
Works, thanks!
