### ISSUE TITLE
Support RedHat

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#26]
Whoops! I had been developing against CentOS this whole time, in preparation for our real servers (RHEL). (In the past, I've had trouble trying to run RHEL locally, due to licensing issues, so I run CentOS to test what I develop for RHEL.) I finally have it to the point where my Ops colleague ran it and...

`FAILED! => {"changed": false, "msg": "Distribution RedHat is not supported by this role!"}`

I didn't realize that this role didn't explicitly accommodate RedHat.

As far as I know, it would just be another simple synonym for CentOS, and CentOS version numbers mirror RHEL's.

**Comment by haxorof** [comment]
Hi @jamiejackson
The thing is that this role is created for Docker CE and to run on RedHat Docker requires Docker EE. Have a look on the Docker documentation here: https://docs.docker.com/engine/installation/

**Comment by jamiejackson** [comment]
That's a good point. I needed it, though, so I added it (see PR). I also added a disclaimer about Linux Mint and RHEL.

**Comment by haxorof** [comment]
Thanks @jamiejackson for the PR. 

I will have a look, hopefully some time before Monday.
