### ISSUE TITLE
Downgrade from Edge to Stable

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#30]
I had been running with edge, but I ran into this: https://github.com/docker/for-linux/issues/211

What's the cleanest way to downgrade to stable, and should the role support downgrades (e.g., remove the edge repo and package and install the latest from stable)?

**Comment by jamiejackson** [comment]
Looks like the role handles disabling of the edge repo when `docker_enable_ce_edge: false`, so running `yum remove docker-ce` before re-running the role seems to take care of everything.

Pretty easy workaround, but I'll leave you to consider whether to support downgrades.

**Comment by haxorof** [comment]
Thanks @jamiejackson

I will think about it a bit and see if it would be a good fit or not. The workaround is quite easy.

Cheers!

**Comment by haxorof** [comment]
I will close this issue because this will not be implemented. Reason is that now Docker edge channel is deprecated and it has become a bit more complicated because docker seems to split up packages also to some cli package etc.
