### ISSUE TITLE
Is MountFlags=slave still necessary?

### ISSUE THREAD

**Issue by jamiejackson** [haxorof/ansible-role-docker-ce#34]
I have to admit that a lot of this configuration is over my head (some of it slightly, some of it completely), but I wanted to bring up a potential development.

I'm wondering if the [systemd drop in for `MountFlags`](https://github.com/haxorof/ansible-role-docker-ce/blob/5a639c0d3e0f1da401ac042adf17afbc27455d95/files/etc/systemd/system/docker.service.d/mountflags-slave.conf) is still necessary, given some recent Docker patches: https://github.com/moby/moby/issues/34538#issuecomment-376172904

What's your take?

**Comment by haxorof** [comment]
I am thinking about introducing a variable like `docker_disable_mount_flag_fix` but default that to `no` to not break any existing things with is using this role today.

What do you think about that @jamiejackson to start with?

**Comment by jamiejackson** [comment]
I guess it's either that or start a backwards-incompatible new release. From what I gather, that `MountFlags` workaround will become less and less relevant as people upgrade Docker versions, but I guess now may not be the time to remove it. Maybe the role could introduce and deprecate (with a warning) your new variable all at once. ;-)

In any case, I think it might be a good idea ([as you mentioned](https://github.com/haxorof/ansible-role-docker-ce/issues/33#issuecomment-379312151)) to throw an error for problematic options combinations (like `MountFlags=slave` + `live-restore: true`), so the role doesn't have to deal with auto-toggling options.

**Comment by haxorof** [comment]
I think I close this issue and the fixed made in #35 will be good for now. Related to the future if someone want have some systemd drop-ins for Docker I think I leave that until a demand for it appears. 😄
