### ISSUE TITLE
Add support to allow users to be added to the docker group

### ISSUE THREAD

**Issue by haxorof** [haxorof/ansible-role-docker-ce#53]
Add variable where you can specify `docker_users` to be added to the docker group

**Comment by simongreen-net** [comment]
Hi,

Are you working on this? I'm happy to do it if not, and submit a pull request this week with the change.

**Comment by haxorof** [comment]
Hi @simongreen-net
Many thanks for offering your help but I have an implementation ready and working on one more thing but will push that today I hope. I need to do some additional tests but can push what I got before that. :smile:

Cheers!

**Comment by haxorof** [comment]
@simongreen-net Pushed the changed and you can have a look at it if you fetch it on master. Will do some more fixing on another ticket before doing release.

Cheers!
