### ISSUE TITLE
Missing docker.service.d directory

### ISSUE THREAD

**Issue by britishbadger** [haxorof/ansible-role-docker-ce#6]
Excellent ansible role, much better than my own. I did however have a few issues, the first was I had to add:

- name: Ensure etc/systemd/system/docker.service.d directory exists
  file: path=/etc/systemd/system/docker.service.d state=directory

to main-Storage.yml. Unfortunately I can't submit a pull request at present.

**Comment by haxorof** [comment]
Thanks @britishbadger for reporting this.

I will make a fix for that probably today.
