### ISSUE TITLE
Failure on Fedora 30

### ISSUE THREAD

**Issue by ndusart** [haxorof/ansible-role-docker-ce#93]
Hi,

This role does not work on F30 as python2-dnf has been removed from repositories.
This should be replaced by python3-dnf on this release.

**Comment by ndusart** [comment]
https://github.com/haxorof/ansible-role-docker-ce/blob/bc3abe26f34c0c176f71ebbf6b62fd3d8b208c78/tasks/setup-repository-Fedora.yml#L4

Is it really necessary to make this check for `python2-dnf` ?
It seems that the `package` module is already doing this and since Ansible 2.8 the python interpreter version is autodetected.

**Comment by haxorof** [comment]
Thanks for reporting this! I keep compatibility with the lowest supported version of Ansible and it is 2.6 right now. I will look into a fix for this hopefully end of this week.

Cheers!

**Comment by haxorof** [comment]
Just tried to install Docker CE on a Fedora 30 but it seems that container.io library dependency does not exist so it fails in both test and nightly channel. I will continue to work on better support for Python 3 in general in this role.

**Comment by haxorof** [comment]
Have I understood you correctly that you tested to install on Fedora 30 with python 3 and version 2.4.1 of this role and it worked? Has Docker released a version which works on Fedora 30?

**Comment by ndusart** [comment]
Actually, I didn't try to install Docker. It worked on a system with docker already installed from a previous version of Fedora.

I can try with a complete new installation when I get the time to.

**Comment by haxorof** [comment]
Waiting for issue to be closed: https://github.com/docker/for-linux/issues/600

**Comment by haxorof** [comment]
Docker CE for Fedora 30 available when selecting nightly channel at least
