### ISSUE TITLE
RHEL: handling repos NOT via subscription-manager

### ISSUE THREAD

**Issue by sfuerte** [haxorof/ansible-role-docker-ce#96]
Hi,

Is it possible to implement handling repos in RHEL **NOT** via `subscription-manager`? Either by default, or have it configurable? Or if it's not available then do it via `yum-config-manager`?

A case: an organization has its own copy of repos and points/proxies all requests to it. So there is no active subscriptions on internal VMs, especially those for dev and test purposes:
```
# subscription-manager repos --list
This system has no repositories available through subscriptions.
```

As a result, the role fails upon execution:
```
fatal: [<server>]: FAILED! => {"changed": true, "cmd": "subscription-manager repos --enable=rhel-7-server-extras-rpms", "delta": "0:00:00.413478", "end": "2019-05-30 08:48:47.087075", "msg": "non-zero return code", "rc": 1, "start": "2019-05-30 08:48:46.673597", "stderr": "", "stderr_lines": [], "stdout": "Error: 'rhel-7-server-extras-rpms' does not match a valid repository ID. Use \"subscription-manager repos --list\" to see valid repositories.", "stdout_lines": ["Error: 'rhel-7-server-extras-rpms' does not match a valid repository ID. Use \"subscription-manager repos --list\" to see valid repositories."]}
```

I have a quick [cratchie] fix in the scripts to update the role upon installation, but really would love to have a way for it embedded in the role, so there wouldn't be any need to override it every time.
```
sed -i 's/subscription-manager repos \-\-list-enabled | grep rhel-7-server-extras-rpms/yum repolist all | grep RHEL_7_Extras_repo | grep enabled/' /etc/ansible/roles/haxorof.docker_ce/tasks/setup-repository-RedHat.yml
sed -i 's/subscription-manager repos --enable=rhel-7-server-extras-rpms/yum-config-manager --enable RHEL_7_Extras_repo/' /etc/ansible/roles/haxorof.docker_ce/tasks/setup-repository-RedHat.yml
```

**Comment by haxorof** [comment]
Thanks @sfuerte! I will have a look at this.

**Comment by haxorof** [comment]
I have created a default configuration (`docker_rhel_repos`) that you now can override. The configuration that you would require is the following:
```yaml
docker_rhel_repos:
  - id: RHEL_7_Extras_repo
    repo_manager: yum
    state: enabled
```
Please try it out and tell me if it works for you or not.

Cheers!

**Comment by haxorof** [comment]
Please reopen if the mechanism provided is not enough.

Cheers!
